name: CI
on:
  push:
  workflow_dispatch:
env:
  NODE_VERSION: 19.7.0
permissions:
  contents: write
jobs:
  ci:
    environment:
      name: ci
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: ci
        with:
          path: |
            ~/.npm
            ~/.node
            !~/.m2/repository/com/github/daggerok
          key: ${{ runner.os }}-${{ hashFiles('**/package.json', '**/package-lock.json') }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm i -E
      - run: npm run build
      - run: npm_config_yes=true npx npm-check-updates -u
      - run: npm run clean
      - run: npm run clear
      - run: npm i -E
      - run: npm run build
