name: CI
on:
  pull_request: 
  workflow_dispatch:
jobs:
  # Reusable bun env:
  bun:
    uses: ./.github/workflows/bun.yml
  # Testing job:
  tests:
    needs: bun
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/cache@v4
        id: ci
        with:
          path: |
            !~/.m2
            ~/.bun
            ~/.npm
            ~/.node
          key: ${{ runner.os }}-${{ hashFiles('**/workflows/*.yml', '**/package.json') }}
      - run: echo "${{ needs.bun.outputs.BUN_BIN }}" >> "$GITHUB_PATH"
      - run: bun install -E
      - run: bun run build
      - run: bunx npm-check-updates -u
      - run: bun run clean
      - run: bun run clear
      - run: bun install -E
      - run: bun run build
      - run: bunx serve src/.vuepress/dist &
      - run: curl http://localhost:3000/blog/2024-ICT/
      - run: curl http://localhost:3000/blog/2023-ICT/
      - run: curl http://localhost:3000/blog/2022-ICT/
