name: GitHub Pages
on:
  push:
    branches: ['master']
  workflow_dispatch:
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  bun:
    uses: ./.github/workflows/bun.yml
  build:
    needs: bun
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - uses: actions/cache@v4
        id: ci
        with:
          path: |
            !~/.m2
            ~/.bun
            ~/.npm
            ~/.node
            ~/.local
          key: ${{ runner.os }}-${{ hashFiles('**/workflows/*.yml', '**/package.json') }}
      #- run: echo "${{ needs.bun.outputs.BUN_BIN }}" >> "$GITHUB_PATH" # because of ~/.local/bin
      - run: bun install -E
      - run: bun run build-github-pages
      - name: Fix permissions
        run: |
          chmod -c -R +rX ".vuepress/dist/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
  # Deployment Step 1: Upload artifacts
  # https://github.com/actions/upload-pages-artifact?tab=readme-ov-file#usage
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: src/.vuepress/dist
  # Deployment Step 2:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
