name: Deploy custom VuePress blog with GitHub Pages artifacts
on:
  push:
    branches: ["master"]
  workflow_dispatch:
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true
# Jobs:
jobs:
  bun:
    uses: ./.github/workflows/bun.yml
  # Build job:
  build:
    needs: bun
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - uses: actions/cache@v4
        id: ci
        with:
          path: |
            !~/.m2
            ~/.bun
            ~/.npm
            ~/.node
          key: ${{ runner.os }}-${{ hashFiles('**/workflows/*.yml', '**/package.json', '**/package-lock.json') }}
      - run: echo "${{ needs.bun.outputs.BUN_BIN }}" >> "$GITHUB_PATH"
      - run: bun install -E
      - run: bun run build-github-pages
      - name: Fix permissions
        run: |
          chmod -c -R +rX ".vuepress/dist/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
      - name: Upload artifact
        #uses: actions/upload-artifact@v4
        #uses: actions/upload-pages-artifact@v1
        uses: actions/upload-pages-artifact@v2
        with:
          name: github-pages
          path: .vuepress/dist
  # Deployment job:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
        #uses: actions/deploy-pages@v4
